Add Cosmos DB to adopt ring
pagopa/technology-radar pull request #56
Opened 2024-01-15 10:15 UTC by Krusty93

- [X] I've added a short description of the entry that
      clarifies what it does and why it's useful
- [X] I've added links to the entry's documentation and/or
      website
- [X] My frontmatter is correct, complete and follows the
      format specified in the [README](../README.md)
- [X] In case the entry is in the `adopt` category: I've
      added at least one reference to showcase the entry usage
      among our organization
- [X] I've described at least one use case for the entry

2024-01-15 11:30 UTC, gunzip commented on radar/platforms-and-services/azure-cosmosdb.md
> +We use Azure Cosmos DB in several applications, usually with SQL or Mongo API.
I'd avoid Mongodb API since they're not first support according to a call we had with Microsoft.

2024-01-18 07:21 UTC, gunzip requested changes

2024-01-18 07:21 UTC, gunzip commented on radar/platforms-and-services/azure-cosmosdb.md
> +We use Azure Cosmos DB in several applications, usually with SQL API.
```suggestion
We utilize Azure Cosmos DB across multiple applications, predominantly employing the SQL API, which receives excellent support directly from the vendor. 
```

2024-01-18 07:21 UTC, gunzip approved these changes
lgtm

2024-01-19 10:00 UTC, iwoak approved these changes

2024-01-19 10:00 UTC, merged